# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies without running prepare scripts
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Build the project explicitly
RUN npm run build

# Expose port for HTTP server
EXPOSE 3000

# Set default PORT environment variable
ENV PORT=3000

# Start the MCP server in HTTP mode
CMD [ "node", "dist/index.js" ]
